package pojo;
// Generated May 25, 2016 2:59:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Device generated by hbm2java
 */
@Entity
@Table(name="device"
    ,catalog="zooba_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="token") 
)
public class Device  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String token;

    public Device() {
    }

    public Device(User user, String token) {
       this.user = user;
       this.token = token;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="token", unique=true, nullable=false)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }




}


